name = "cf_ai_studybuddy"
main = "src/server.ts"
compatibility_date = "2025-10-01"

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "ChatAgent"
class_name = "ChatAgent"

[[migrations]]
tag = "v1"
new_classes = ["ChatAgent"]

[assets]
binding = "ASSETS"
directory = "public"
